
--boundary_.oOo._jU+bnin1Mq9HNFYjqMsBLTx0qZvY0f9w
Content-Length: 466
Content-Type: application/octet-stream
X-File-MD5: 592ccb3120f73b4ab561f824d824eb9d
X-File-Mtime: 1709774054
X-File-Path: /Git/Librography/Setup-Linux/setup-files.sh

#!/bin/sh

sudo rm -rf /opt/Librography
mkdir /opt
sudo pacman -S p7zip
sudo 7z x ../setup/data -o/opt/ -aoa
sudo chown root -R /opt/Librography
sudo chmod 777 -R /opt/Librography
cp DBType /opt/Librography/
#touch /opt/Librography/DBType
#echo "mysql" >> /opt/Librography/DBType 
#sed -i 's/^[^0-9]*//' /opt/Librography/DBType
cp ../dist/Librography.jar /opt/Librography/
cp Librography.sh /opt/Librography/
sudo chmod a+rx /opt/Librography/Librography.jar

#pause

--boundary_.oOo._jU+bnin1Mq9HNFYjqMsBLTx0qZvY0f9w
Content-Length: 1154
Content-Type: application/octet-stream
X-File-MD5: 004045fac88a1b8a84b6f44d3b5c9b3f
X-File-Mtime: 1709774054
X-File-Path: /Git/Librography/Setup-Linux/setup-mariadb-arch.sh

#!/bin/sh


echo "Script is executed as : `whoami`"

#var0=$(who am i | awk '{print $1}')
#echo "var0 is $var0"

server=127.0.0.1
dbname=applibrography
dbuser=applibrography
dbuserpassword=gowl


if nc -z $server 3306 2>/dev/null; then
    echo "$server ✓ - MariaDB Server is installed!"
    echo "Proceeding to configuration:"
    sudo mysql -uroot --execute="CREATE DATABASE $dbname"; #change to variables
    sudo mysql -uroot --execute="CREATE USER '$dbuser'@'localhost' IDENTIFIED BY '$dbuserpassword';"
	sudo mysql -uroot --execute="GRANT ALL PRIVILEGES ON $dbuser.* TO '$dbuser'@'localhost';"
	sudo mysql -uroot --execute="FLUSH PRIVILEGES;"
	sudo mysql -uroot --execute="source script.sql"
else
    echo "$server ✗ - MariaDb is not Installed!!"
    echo "Do tou wanto to install?"
    # if else aqui com resposta""
    sudo pacman -Syu
    sudo pacman -S mariadb
    sudo mariadb-install-db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
    sudo systemctl start mariadb.service
    sudo systemctl enable mariadb.service
fi



# PS3='Choose your firewal profile: '


#mysql -uroot -p%rootpassword% --execute="CREATE DATABASE %dbname%;"

--boundary_.oOo._jU+bnin1Mq9HNFYjqMsBLTx0qZvY0f9w
Content-Length: 1851
Content-Type: application/octet-stream
X-File-MD5: 9c718e76213bef632236696c5444881f
X-File-Mtime: 1709774054
X-File-Path: /Git/Librography/Setup-Linux/setupMysql.bat

@echo off
:start
netstat -o -n -a | findstr 3306
if %ERRORLEVEL% equ 0 goto FOUND
echo MySql not found or not usisng default port 3306...
ECHO Do you wanto open open browser to download it?
ECHO 1. yes
ECHO 2. no
set /p choice=Choose your option.
if '%choice%'=='' ECHO "%choice%" is not valid please try again
if '%choice%'=='1' goto open
if '%choice%'=='2' goto FIN
ECHO.
goto start
:open
echo opening the Mysql download link....
pause
START Https://dev.mysql.com/downloads/installer/
ECHO you can download the setup fromlink now and after install it we will continue the setup
ECHO choose the default options on setup and don`t forget to take a note of the root password
pause
Rem :continue
Rem echo ok
goto start
Rem goto FIN
:FOUND
echo port found. It mean the Mysql is installed
echo we can continue the setup...
pause
:FIN

echo .
echo .
@echo off
rem ------------------------------------------------
echo Creating access to user. Waiting ...
echo Enter the MySql root password:
set /p rootpassword=
set dbname=applibrography
set dbuser=applibrography
set userpassword=gowl
Rem "C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql.exe" "--defaults-file=C:\ProgramData\MySQL\MySQL Server 5.7\my.ini" "-uroot" "-p"
SET PATH=%PATH%;C:\Program Files\MySQL\MySQL Server 5.7\bin
mysql -uroot -p%rootpassword% --execute="CREATE DATABASE %dbname%;"
mysql -uroot -p%rootpassword% --execute="CREATE USER '%dbuser%'@'localhost' IDENTIFIED BY '%userpassword%';"
mysql  -uroot -p%rootpassword% --execute="GRANT ALL PRIVILEGES ON %dbuser%.* TO '%dbuser%'@'localhost';"

mysql  -uroot -p%rootpassword% --execute="FLUSH PRIVILEGES;"
mysql  -uroot -p%rootpassword% --execute="source script.sql"
echo Done.
echo "MySQL user created."
echo "Username:   %dbuser%"
echo "Password:   %userpassword%"
rem ------------------------------------------------
echo .
echo . 

--boundary_.oOo._jU+bnin1Mq9HNFYjqMsBLTx0qZvY0f9w
Content-Length: 1973
Content-Type: application/octet-stream
X-File-MD5: c8e8e4021c56b3e70a8e6da55fb39dcc
X-File-Mtime: 1709774054
X-File-Path: /Git/Librography/Setup-Windows/Install_Files/InnoScript-Win_0.1-beta.iss

; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Librography"
#define MyAppVersion "0.1-beta"
#define MyAppPublisher "FlashInformatics, Inc."
#define MyAppURL "https://www.librography.site/"
#define MyAppExeName "Librography.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{EAC392A1-AC02-4CE1-9B71-18B555A85097}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\{#MyAppName}
DisableDirPage=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=F:\Desktop\goldenowl\Installers\InnoSetupFiles
OutputBaseFilename=LibrographyInstaller_0.1-beta
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Librography\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Librography\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent


--boundary_.oOo._jU+bnin1Mq9HNFYjqMsBLTx0qZvY0f9w
Content-Length: 1600
Content-Type: application/octet-stream
X-File-MD5: 82856cc6b57a8f09f9b3d87b51a5b177
X-File-Mtime: 1709774054
X-File-Path: /Git/Librography/Setup-Windows/Install_Files/mysql _install.bat

@echo off

echo Criando a pasta data, utilizadas pelo MySQL

set mypath=C:\Librography

net stop MySql

set mysqlpath=%mypath%\mysql

if not exist "%mysqlpath%\data" mkdir "%mysqlpath%\data"

echo Inicializando o MySQL. Criando o conteúdo da pasta data

"%mysqlpath%/bin/mysqld.exe" --initialize-insecure --user=mysql --basedir="%mysqlpath%" --datadir="%mysqlpath%\data"

echo Definindo o MySQL como um serviço

"%mysqlpath%\bin\mysqld.exe" --install MySQL

echo Iniciando o serviço criado

sc start MySQL

echo Verificando se o serviço esta ativo

:INITDATA
sc query "MySQL" | find "RUNNING"
if "%ERRORLEVEL%"=="0" (
	echo Serviço ativo ...
	
	echo Configurando a base de dados...

	


    echo Definindo uma senha para o usuário root...

	:: "%mysqlpath%\bin\mysql.exe" -u root --skip-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'goldenowl';"

	:: echo Criando o usuário utilizado pela aplicação e atribuindo as permissões dele

	:: "%mysqlpath%\bin\mysql.exe" -u root -p goldenowl -e "CREATE USER 'appLibrography'@'localhost' IDENTIFIED BY 'app1Librography';GRANT CREATE, SELECT, INSERT, UPDATE, DELETE ON *.* TO 'appLibrography'@'localhost';FLUSH PRIVILEGES;"

	::echo Criando o banco de dados da aplicação

	::"%mysqlpath%\bin\mysql.exe" -u appLibrography -p app1Librography -e "CREATE DATABASE appLibrography;"

	:: echo Criando a tabela utilizada pela a aplicação

	:: "%mysqlpath%\bin\mysql.exe" -i C:\Librography\Install_F